job:
  KIND: TrainingJob
  inputs:
    KIND: CsvReader
    path: data/processed/inputs_train.csv
  targets:
    KIND: CsvReader
    path: data/processed/targets_train.csv
  use_best_from_tuning: true
  model:
    KIND: XGBoost
  metrics:
    - KIND: SklearnMetric
      name: RMSE
      sklearn_name: root_mean_squared_error
      greater_is_better: false
    - KIND: SklearnMetric
      name: R2
      sklearn_name: r2_score
      greater_is_better: true
